export default {
	container: document.querySelector('.container'),
	menuList: document.querySelector('.menu'),
	caloriesText: document.querySelector('.calories--text'),
	caloriesIcon: document.querySelector('.calories--icon'),
	mainContainer: document.querySelector('main.foods'),
	btnPrev: document.querySelector('.btn__prev'),
	btnNext: document.querySelector('.btn__next'),
	footerBlock: document.querySelector('footer .bottom'),
	footerMenu: document.querySelector('.bottom__menu'),
	footerLangList: document.querySelector('.bottom__flags'),
	footerMenuLang: document.querySelector('.bottom__menu--language'),
	overlay: document.querySelector('.overlay'),
	setGramsWrapper: document.querySelector('.overlay__set-grams__wrapper'),
	setGramsContainer: document.querySelector('.overlay__set-grams__container'),
	setGramsImg: document.querySelector('.overlay__set-grams--image'),
	setGramsImgPseudo: document.querySelector('.overlay__set-grams--image--pseudo'),
	setGramsInputContainer: document.querySelector('.overlay__set-grams__input'),
	setGramsInputNumber: document.querySelector('.overlay__set-grams__input--number'),
	setGramsInputSymbol: document.querySelector('.overlay__set-grams__input--symbol'),
	setGramsBtnInc: document.querySelector('.overlay__set-grams__input--btns__btn--inc'),
	setGramsBtnDec: document.querySelector('.overlay__set-grams__input--btns__btn--dec'),
	setGramsBtn: document.querySelector('.overlay__set-grams__btn')

	// overlayContactContainer: document.querySelector('.overlay__contact__container'),
	// overlayContactForm: document.querySelector('.overlay__contact__container form'),
	// overlayContactName: document.querySelector('.overlay__contact--input[name="name"]'),
	// overlayContactEmail: document.querySelector('.overlay__contact--input[name="email"]'),
	// overlayContactMessage: document.querySelector('textarea.overlay__contact--input'),
	// overlayContactBtn: document.querySelector('.overlay__contact--btn')
};